on:
  push:
    branches: [master]
  pull_request:
name: Test
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.14.9, 1.15.2]
        os: [ubuntu-18.04, macos-10.15, windows-2019]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Test
        run: make test

  lint:
    runs-on: ubuntu-18.04
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15.2
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Lint
        run: make lint
